//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Gören Kayıt Silinemez!.
        /// </summary>
        internal static string _50000 {
            get {
                return ResourceManager.GetString("_50000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodu Giriniz.
        /// </summary>
        internal static string _50001 {
            get {
                return ResourceManager.GetString("_50001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı Giriniz.
        /// </summary>
        internal static string _50002 {
            get {
                return ResourceManager.GetString("_50002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Tekil Olmalıdır!.
        /// </summary>
        internal static string _50003 {
            get {
                return ResourceManager.GetString("_50003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Bulunamadı!.
        /// </summary>
        internal static string _50004 {
            get {
                return ResourceManager.GetString("_50004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıfır Girilemez!.
        /// </summary>
        internal static string _50005 {
            get {
                return ResourceManager.GetString("_50005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Türevi Seçiniz!.
        /// </summary>
        internal static string _50006 {
            get {
                return ResourceManager.GetString("_50006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kayıt daha önce oluşturulmuş!.
        /// </summary>
        internal static string _50007 {
            get {
                return ResourceManager.GetString("_50007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Tekil Olmalıdır!.
        /// </summary>
        internal static string _50008 {
            get {
                return ResourceManager.GetString("_50008", resourceCulture);
            }
        }
    }
}
